### ISSUE TITLE
LTC2321-16

### ISSUE THREAD

**Issue by darkcurrent** [kelu124/bomanz#1]
Hi Ghosh,

[LTC2321-16](http://cds.linear.com/docs/en/datasheet/232116fa.pdf) is excellent ADC _(16 bit, 2Msps Throughput Rate)_ considering its high bit depth, high sampling rate and reasonably low price . Since high bit rate sampling is very essential in many application areas, maybe you can use this ADC IC in your further ADC board projects like Bomanz project.

Regards,

**Comment by kelu124** [comment]
Hi @darkcurrent - and thanks for your feedback!
If speed is what you are looking for, the performances of the current pHAT are at around 10Msps, at 8 bit. Would this fit in with your _high bit rate sampling_ requirement? Note that this is possible because the ADC speaks in serial with the raspberry.
If your own target is 2Msps, feel free to try to implement one. The issue then in using the LTC2321-16  is that your communication protocol is at least of 2Msps * 16 bit -> 36MHz clock (actually more, due to overheads), which the raspberry may or may not tolerate.
That being said, the kernel module also allows to slow down the clock, so you may also reach 2Msps using either option (ADC08200 or the CA3306) to acquire your signal.
Hope that helps!
